export const mockData = [
	{
		nbmonId: 2,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		hatchedAt: 1650957830,
		isHatchable: false,
		transferredAt: 1650957407,
		hatchingDuration: 300,
		strongAgainst: ["Fire", "Water", "Electric", "Crystal", "Psychic", "Toxic"],
		weakAgainst: [
			"Ordinary",
			"Earth",
			"Wind",
			"Frost",
			"Nature",
			"Brawler",
			"Reptile",
		],
		resistantTo: ["Fire", "Electric", "Wind", "Psychic", "Reptile", "Toxic"],
		vulnerableTo: ["Ordinary", "Water", "Frost", "Nature", "Brawler"],
		gender: "Male",
		rarity: "Common",
		mutation: "Mutated",
		mutationType: "Fire",
		species: "Origin",
		genus: "Todillo",
		fertility: "3000",
		fertilityDeduction: 1000,
		types: ["Reptile", "Earth"],
		healthPotential: 17,
		energyPotential: 11,
		attackPotential: 0,
		defensePotential: 3,
		spAtkPotential: 3,
		spDefPotential: 15,
		speedPotential: 0,
		passives: ["Chitin Plating", "Heat Absorption"],
		isEgg: false,
	},
];
