export const mockData = [
	{
		nbmonId: "1",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1646432245",
		transferredAt: "1646432245",
		hatchingDuration: "100",
		gender: "male",
		rarity: "rare",
		mutation: "not mutated",
		mutation_value: null,
		species: "wild",
		genera: "birvo",
		fertility: "2500",
		types: ["melee", "water"],
		healthPotential: null,
		energyPotential: null,
		attackPotential: null,
		defensePotential: null,
		spAtkPotential: null,
		spDefPotential: null,
		speedPotential: null,
		firstPassive: null,
		secondPassive: null,
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "122",
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		bornAt: 1649958229,
		isHatchable: true,
		transferredAt: 1649958229,
		hatchingDuration: 300,
		gender: null,
		rarity: null,
		mutation: null,
		species: null,
		genera: null,
		fertility: null,
		types: [null, null],
		healthPotential: null,
		energyPotential: null,
		attackPotential: null,
		defensePotential: null,
		spAtkPotential: null,
		spDefPotential: null,
		speedPotential: null,
		passives: [null, null],
		isEgg: true,
	},
	{
		nbmonId: "2",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1646432254",
		transferredAt: "1646432254",
		hatchingDuration: "100",
		gender: "female",
		rarity: "rare",
		mutation: "not mutated",
		mutation_value: null,
		species: "origin",
		genera: "lamox",
		fertility: "2000",
		types: ["melee", "water"],
		healthPotential: null,
		energyPotential: null,
		attackPotential: null,
		defensePotential: null,
		spAtkPotential: null,
		spDefPotential: null,
		speedPotential: null,
		firstPassive: null,
		secondPassive: null,
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "4",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1647985820",
		transferredAt: "1647985820",
		hatchingDuration: "100000",
		gender: "male",
		rarity: "rare",
		mutation: "not mutated",
		mutation_value: null,
		species: "origin",
		genera: "lamox",
		fertility: "3000",
		types: ["electric", "spirit"],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "5",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1647985825",
		transferredAt: "1647985825",
		hatchingDuration: "100000",
		gender: "female",
		rarity: "epic",
		mutation: "mutated",
		mutation_value: "fire",
		species: "origin",
		genera: "heree",
		fertility: "3000",
		types: ["nature", "spirit"],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "6",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1647985809",
		transferredAt: "1647985809",
		hatchingDuration: "100000",
		gender: "male",
		rarity: "common",
		mutation: "mutated",
		mutation_value: "water",
		species: "hybrid",
		genera: "milnas",
		fertility: "3000",
		types: ["fire", "wind"],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "7",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1646432245",
		transferredAt: "1646432245",
		hatchingDuration: "100000",
		gender: "female",
		rarity: "uncommon",
		mutation: "mutated",
		mutation_value: "wind",
		species: "wild",
		genera: "schoggi",
		fertility: "3000",
		types: ["digital", "toxic"],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "8",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1646432245",
		transferredAt: "1646432245",
		hatchingDuration: "100000",
		gender: "female",
		rarity: "uncommon",
		mutation: "mutated",
		mutation_value: "brawler",
		species: "wild",
		genera: "dranexx",
		fertility: "1250",
		types: ["fire", "toxic"],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "25",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1646432245",
		transferredAt: "1646432245",
		hatchingDuration: "100000",
		gender: "female",
		rarity: "legendary",
		mutation: "mutated",
		mutation_value: "nature",
		species: "origin",
		genera: "todillo",
		fertility: "1582",
		types: ["crystal", "fire"],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "9",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1646432245",
		transferredAt: "1646432245",
		hatchingDuration: "100000",
		gender: "male",
		rarity: "mythical",
		mutation: "not mutated",
		mutation_value: null,
		species: "hybrid",
		genera: "licorine",
		fertility: "1582",
		types: ["nature", "melee"],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "10",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1646432245",
		transferredAt: "1646432245",
		hatchingDuration: "100000",
		gender: "female",
		rarity: "common",
		mutation: "not mutated",
		mutation_value: null,
		species: "wild",
		genera: "pongu",
		fertility: "2836",
		types: ["melee", "wind"],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "11",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1646432245",
		transferredAt: "1646432245",
		hatchingDuration: "100000",
		gender: "female",
		rarity: "uncommon",
		mutation: "mutated",
		mutation_value: "electric",
		species: "wild",
		genera: "prawdek",
		fertility: "1969",
		types: ["toxic", null],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "12",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1646432245",
		transferredAt: "1646432245",
		hatchingDuration: "100000",
		gender: "male",
		rarity: "common",
		mutation: "mutated",
		mutation_value: "psychic",
		species: "wild",
		genera: "roggo",
		fertility: "2903",
		types: ["neutral", "nature"],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
	{
		nbmonId: "13",
		maleParent: null,
		femaleParent: null,
		owner: "0x6ef0f724e780E5D3aD66f2A4FCbEF64A774eA796",
		isTradable: true,
		isBreedable: true,
		hatchedAt: "1646432245",
		transferredAt: "1646432245",
		hatchingDuration: "100000",
		gender: "female",
		rarity: "legendary",
		mutation: "not mutated",
		mutation_value: null,
		species: "hybrid",
		genera: "todillo",
		fertility: "873",
		types: ["fire", "nature"],
		healthPotential: "5",
		energyPotential: "13",
		attackPotential: "22",
		defensePotential: "16",
		spAtkPotential: "4",
		spDefPotential: "11",
		speedPotential: "8",
		firstPassive: "Passive A",
		secondPassive: "Passive B",
		firstInheritedPassive: null,
		secondInheritedPassive: null,
		firstInheritedMove: null,
		secondInheritedMove: null,
		isEgg: false,
	},
];
