import { useContext, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useMoralis } from "react-moralis";
import AppContext from "context/AppContext";

export default function Home() {
	const { authenticate, isAuthenticated, logout } = useMoralis();
	const { web3 } = useContext(AppContext);

	useEffect(() => {
		console.log(web3);
	}, [web3]);

	return (
		<div className={styles.container}>
			<Head>
				<title>Realm Hunter | Marketplace</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Hello World :) | Development happens here...
				</h1>
			</main>
		</div>
	);
}
